<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class CurrenciesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('currencies')->delete();
        $currencies = array(
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'AFN' , 'name' => 'Afghani', 'symbol' => '؋' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'ALL' , 'name' => 'Lek', 'symbol' => 'Lek' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'ANG' , 'name' => 'Netherlands Antillian Guilder', 'symbol' => 'ƒ' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'ARS' , 'name' => 'Argentine Peso', 'symbol' => '$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'AUD' , 'name' => 'Australian Dollar', 'symbol' => '$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'AWG' , 'name' => 'Aruban Guilder', 'symbol' => 'ƒ' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'AZN' , 'name' => 'Azerbaijanian Manat', 'symbol' => 'ман' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'BAM' , 'name' => 'Convertible Marks', 'symbol' => 'KM' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'BBD' , 'name' => 'Barbados Dollar', 'symbol' => '$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'BGN' , 'name' => 'Bulgarian Lev', 'symbol' => 'лв' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'BMD' , 'name' => 'Bermudian Dollar', 'symbol' => '$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'BND' , 'name' => 'Brunei Dollar', 'symbol' => '$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'BOB' , 'name' => 'BOV Boliviano Mvdol', 'symbol' => '$b' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'BRL' , 'name' => 'Brazilian Real', 'symbol' => 'R$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'BSD' , 'name' => 'Bahamian Dollar', 'symbol' => '$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'BWP' , 'name' => 'Pula', 'symbol' => 'P' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'BYR' , 'name' => 'Belarussian Ruble', 'symbol' => 'p.' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'BZD' , 'name' => 'Belize Dollar', 'symbol' => 'BZ$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'CAD' , 'name' => 'Canadian Dollar', 'symbol' => '$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'CHF' , 'name' => 'Swiss Franc', 'symbol' => 'CHF' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'CLP' , 'name' => 'CLF Chilean Peso Unidades de fomento', 'symbol' => '$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'CNY' , 'name' => 'Yuan Renminbi', 'symbol' => '¥' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'COP' , 'name' => 'COU Colombian Peso Unidad de Valor Real', 'symbol' => '$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'CRC' , 'name' => 'Costa Rican Colon', 'symbol' => '₡' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'CUP' , 'name' => 'CUC Cuban Peso Peso Convertible', 'symbol' => '₱' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'CZK' , 'name' => 'Czech Koruna', 'symbol' => 'Kč' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'DKK' , 'name' => 'Danish Krone', 'symbol' => 'kr' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'DOP' , 'name' => 'Dominican Peso', 'symbol' => 'RD$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'EGP' , 'name' => 'Egyptian Pound', 'symbol' => '£' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'EUR' , 'name' => 'Euro', 'symbol' => '€' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'FJD' , 'name' => 'Fiji Dollar', 'symbol' => '$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'FKP' , 'name' => 'Falkland Islands Pound', 'symbol' => '£' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'GBP' , 'name' => 'Pound Sterling', 'symbol' => '£' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'GIP' , 'name' => 'Gibraltar Pound', 'symbol' => '£' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'GTQ' , 'name' => 'Quetzal', 'symbol' => 'Q' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'GYD' , 'name' => 'Guyana Dollar', 'symbol' => '$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'HKD' , 'name' => 'Hong Kong Dollar', 'symbol' => '$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'HNL' , 'name' => 'Lempira', 'symbol' => 'L' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'HRK' , 'name' => 'Croatian Kuna', 'symbol' => 'kn' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'HUF' , 'name' => 'Forint', 'symbol' => 'Ft' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'IDR' , 'name' => 'Rupiah', 'symbol' => 'Rp' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'ILS' , 'name' => 'New Israeli Sheqel', 'symbol' => '₪' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'IRR' , 'name' => 'Iranian Rial', 'symbol' => '﷼' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'ISK' , 'name' => 'Iceland Krona', 'symbol' => 'kr' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'JMD' , 'name' => 'Jamaican Dollar', 'symbol' => 'J$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'JPY' , 'name' => 'Yen', 'symbol' => '¥' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'KGS' , 'name' => 'Som', 'symbol' => 'лв' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'KHR' , 'name' => 'Riel', 'symbol' => '៛' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'KPW' , 'name' => 'North Korean Won', 'symbol' => '₩' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'KRW' , 'name' => 'Won', 'symbol' => '₩' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'KYD' , 'name' => 'Cayman Islands Dollar', 'symbol' => '$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'KZT' , 'name' => 'Tenge', 'symbol' => 'лв' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'LAK' , 'name' => 'Kip', 'symbol' => '₭' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'LBP' , 'name' => 'Lebanese Pound', 'symbol' => '£' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'LKR' , 'name' => 'Sri Lanka Rupee', 'symbol' => '₨' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'LRD' , 'name' => 'Liberian Dollar', 'symbol' => '$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'LTL' , 'name' => 'Lithuanian Litas', 'symbol' => 'Lt' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'LVL' , 'name' => 'Latvian Lats', 'symbol' => 'Ls' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'MKD' , 'name' => 'Denar', 'symbol' => 'ден' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'MNT' , 'name' => 'Tugrik', 'symbol' => '₮' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'MUR' , 'name' => 'Mauritius Rupee', 'symbol' => '₨' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'MXN' , 'name' => 'MXV Mexican Peso Mexican Unidad de Inversion (UDI)', 'symbol' => '$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'MYR' , 'name' => 'Malaysian Ringgit', 'symbol' => 'RM' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'MZN' , 'name' => 'Metical', 'symbol' => 'MT' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'NGN' , 'name' => 'Naira', 'symbol' => '₦' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'NIO' , 'name' => 'Cordoba Oro', 'symbol' => 'C$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'NOK' , 'name' => 'Norwegian Krone', 'symbol' => 'kr' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'NPR' , 'name' => 'Nepalese Rupee', 'symbol' => '₨' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'NZD' , 'name' => 'New Zealand Dollar', 'symbol' => '$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'OMR' , 'name' => 'Rial Omani', 'symbol' => '﷼' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'PAB' , 'name' => 'USD Balboa US Dollar', 'symbol' => 'B/.' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'PEN' , 'name' => 'Nuevo Sol', 'symbol' => 'S/.' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'PHP' , 'name' => 'Philippine Peso', 'symbol' => 'Php' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'PKR' , 'name' => 'Pakistan Rupee', 'symbol' => '₨' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'PLN' , 'name' => 'Zloty', 'symbol' => 'zł' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'PYG' , 'name' => 'Guarani', 'symbol' => 'Gs' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'QAR' , 'name' => 'Qatari Rial', 'symbol' => '﷼' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'RON' , 'name' => 'New Leu', 'symbol' => 'lei' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'RSD' , 'name' => 'Serbian Dinar', 'symbol' => 'Дин.' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'RUB' , 'name' => 'Russian Ruble', 'symbol' => 'руб' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'SAR' , 'name' => 'Saudi Riyal', 'symbol' => '﷼' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'SBD' , 'name' => 'Solomon Islands Dollar', 'symbol' => '$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'SCR' , 'name' => 'Seychelles Rupee', 'symbol' => '₨' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'SEK' , 'name' => 'Swedish Krona', 'symbol' => 'kr' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'SGD' , 'name' => 'Singapore Dollar', 'symbol' => '$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'SHP' , 'name' => 'Saint Helena Pound', 'symbol' => '£' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'SOS' , 'name' => 'Somali Shilling', 'symbol' => 'S' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'SRD' , 'name' => 'Surinam Dollar', 'symbol' => '$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'SVC' , 'name' => 'USD El Salvador Colon US Dollar', 'symbol' => '$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'SYP' , 'name' => 'Syrian Pound', 'symbol' => '£' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'THB' , 'name' => 'Baht', 'symbol' => '฿' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'TRY' , 'name' => 'Turkish Lira', 'symbol' => 'TL' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'TTD' , 'name' => 'Trinidad and Tobago Dollar', 'symbol' => 'TT$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'TWD' , 'name' => 'New Taiwan Dollar', 'symbol' => 'NT$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'UAH' , 'name' => 'Hryvnia', 'symbol' => '₴' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'USD' , 'name' => 'US Dollar', 'symbol' => '$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'UYU' , 'name' => 'UYI Peso Uruguayo Uruguay Peso en Unidades Indexadas', 'symbol' => '$U' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'UZS' , 'name' => 'Uzbekistan Sum', 'symbol' => 'лв' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'VEF' , 'name' => 'Bolivar Fuerte', 'symbol' => 'Bs' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'VND' , 'name' => 'Dong', 'symbol' => '₫' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'XCD' , 'name' => 'East Caribbean Dollar', 'symbol' => '$' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'YER' , 'name' => 'Yemeni Rial', 'symbol' => '﷼' ),
            array('created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'code' =>'ZAR' , 'name' => 'Rand', 'symbol' => 'R' ),
        );
        DB::table('currencies')->insert($currencies);
    }
}
